_wandb:
    value:
        cli_version: 0.25.0
        e:
            a3xs9b8469scele0lia869ofgg70dbds:
                codePath: runs/main_V0.py
                codePathLocal: main_V0.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "105089261568"
                        used: "37492641792"
                email: sousa.pedro.fernandes@gmail.com
                executable: /usr/local/miniconda3/bin/python
                git:
                    commit: 41738896df9312d0becfb0da567ba0c652087b58
                    remote: https://github.com/brightside51/meddiff.git
                gpu: NVIDIA GeForce GTX 1080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 2560
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce GTX 1080
                      uuid: GPU-0293151b-a229-ddbe-606d-9009c8d60336
                host: 01.ctm-deep-03
                memory:
                    total: "67352727552"
                os: Linux-6.8.0-100-generic-x86_64-with-glibc2.39
                program: /nas-ctm01/homes/pfsousa/meddiff/runs/main_V0.py
                python: CPython 3.13.11
                root: /nas-ctm01/homes/pfsousa/meddiff/runs
                slurm:
                    cluster_name: ctm-slurm
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "8"
                    gtids: "0"
                    job_account: scholar
                    job_cpus_per_node: "8"
                    job_end_time: "1772632866"
                    job_gid: "1000000"
                    job_group: Domain Users
                    job_id: "18618"
                    job_name: bash
                    job_nodelist: 01.ctm-deep-03
                    job_num_nodes: "1"
                    job_partition: gpu_min8gb
                    job_qos: gpu_min8gb
                    job_start_time: "1772028066"
                    job_uid: "1000149"
                    job_user: pfsousa
                    jobid: "18618"
                    launch_node_ipaddr: 10.12.11.17
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: 01.ctm-deep-03
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "10713"
                    pty_win_col: "131"
                    pty_win_row: "38"
                    srun_comm_host: 10.12.11.17
                    srun_comm_port: "10714"
                    step_id: "0"
                    step_launcher_port: "10714"
                    step_nodelist: 01.ctm-deep-03
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /nas-ctm01/homes/pfsousa/meddiff/runs
                    submit_host: ctm-login-02.inesctec.pt
                    task_pid: "604996"
                    tasks_per_node: "1"
                    topology_addr: 01.ctm-deep-03
                    topology_addr_pattern: node
                    umask: "0022"
                startedAt: "2026-02-25T15:11:48.033826Z"
                writerId: a3xs9b8469scele0lia869ofgg70dbds
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.11
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
dataV:
    value: V0
runV:
    value: V0
