wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1772726777
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      3:
      - 13
      - 16
      4: 3.8.20
      5: 0.12.21
      8:
      - 5
dataV:
  desc: null
  value: V0
runV:
  desc: null
  value: V0
